---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-deploy-ext-config
  labels:
    app: "{{ template "app-deploy-fe.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- with .Values.appExtConfig }}
  {{- toYaml . | nindent 2 }}
{{- end }}
